partition:
  name: Common

# Here goes Change reference to be placed into Description of created objects
change: CHG00001 TEST

# Put Virtual server config below
vip:
  name: FCV1NLP-www.fnac.nl-HTTP
  destination: 192.168.0.100
  port: 80
  params:
    ipProtocol: tcp
    profiles:
      - http
      - /Common/wom-default-clientssl
      - /Common/oneconnect
    # iRules
    rules:
      - /Common/_sys_https_redirect

# Put pool config here
pool:
  params:
    # See "help pool" for a description of each loading balancing mode.
    loadBalancingMode: round-robin
    # Specifies the health monitors that the system uses to determine whether it can use this pool for load balancing. The monitor marks the pool up or down based on whether the monitor(s) are successful. You can specify a single monitor, multiple monitors "http and https", or a "min" rule, "min 1 of { http https }". You may remove the monitor by specifying "none".
    monitor: gateway_icmp

# Below nodes to be created \ added as pool members
nodes:
  FCS1WPPPLFWEB1: # Node \ member name
    address: 10.10.10.3
    port: 80
    # Put below 'y' - if node exists and just pool memeber need to be created
    exists: n
  FCS1WPPPLFWEB2:
    address: 10.10.10.4
    port: 80
    exists: n
      
   